---
- name: Playbook for register variable
  hosts: node1
  tasks:
    - name: create a user
      ansible.builtin.user:
        name: justin
        state: present
      register: user_output

    - name: print the output
      ansible.builtin.debug:
        var: user_output.state
