---
- name: Playbook to practice variables
  hosts: india
  vars_files:
    - vars.yml
  tasks:
    - name: create a group - {{ group_name }}
      group:
        name: "{{ group_name }}"
        state: present

    - name: create a user - {{ user_name }}
      user:
        name: "{{ user_name }}"
        state: present
        group: "{{ group_name }}"
